/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingInvestorRouteImport } from './routes/onboarding/investor'
import { Route as OnboardingFounderRouteImport } from './routes/onboarding/founder'
import { Route as DashboardInvestorRouteImport } from './routes/dashboard/investor'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInvestorRoute = OnboardingInvestorRouteImport.update({
  id: '/onboarding/investor',
  path: '/onboarding/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFounderRoute = OnboardingFounderRouteImport.update({
  id: '/onboarding/founder',
  path: '/onboarding/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestorRoute = DashboardInvestorRouteImport.update({
  id: '/dashboard/investor',
  path: '/dashboard/investor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/onboarding/founder': typeof OnboardingFounderRoute
  '/onboarding/investor': typeof OnboardingInvestorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/onboarding/founder': typeof OnboardingFounderRoute
  '/onboarding/investor': typeof OnboardingInvestorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/onboarding/founder': typeof OnboardingFounderRoute
  '/onboarding/investor': typeof OnboardingInvestorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/investor'
    | '/onboarding/founder'
    | '/onboarding/investor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/investor'
    | '/onboarding/founder'
    | '/onboarding/investor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard/investor'
    | '/onboarding/founder'
    | '/onboarding/investor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardInvestorRoute: typeof DashboardInvestorRoute
  OnboardingFounderRoute: typeof OnboardingFounderRoute
  OnboardingInvestorRoute: typeof OnboardingInvestorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/investor': {
      id: '/onboarding/investor'
      path: '/onboarding/investor'
      fullPath: '/onboarding/investor'
      preLoaderRoute: typeof OnboardingInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/founder': {
      id: '/onboarding/founder'
      path: '/onboarding/founder'
      fullPath: '/onboarding/founder'
      preLoaderRoute: typeof OnboardingFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/investor': {
      id: '/dashboard/investor'
      path: '/dashboard/investor'
      fullPath: '/dashboard/investor'
      preLoaderRoute: typeof DashboardInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardInvestorRoute: DashboardInvestorRoute,
  OnboardingFounderRoute: OnboardingFounderRoute,
  OnboardingInvestorRoute: OnboardingInvestorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
